spring.datasource.url=jdbc:h2:mem:smart_campus
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.mongodb.uri=mongodb+srv://ntlewhan_db_user:fctCXJGIi65tKVuM@cluster0.wfwlqvr.mongodb.net/smart_campus?retryWrites=true&w=majority&appName=Cluster0

server.port=8080
