# Application name
spring.application.name=smart-campus-backend

# MongoDB connection string
spring.data.mongodb.uri=mongodb+srv://ntlewhan_db_user:fctCXJGIi65tKVuM@cluster0.wfwlqvr.mongodb.net/smart_campus?retryWrites=true&w=majority&appName=Cluster0

# Server port
server.port=8080

# Logging level for MongoDB
logging.level.org.springframework.data.mongodb=DEBUG
