ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_provider VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_number VARCHAR(30);
